# Generated by Django 3.2.7 on 2021-09-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physician',
            name='hospital',
        ),
        migrations.AddField(
            model_name='physician',
            name='hospital',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='web.Hospital'),
        ),
    ]
