# Generated by Django 3.2.7 on 2021-09-11 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210911_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='physician_name',
        ),
    ]
